export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
export const LOG_OUT = 'LOG_OUT';

export const GET_CONTACTS_LOADING = 'GET_CONTACTS_LOADING';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAIL = 'GET_CONTACTS_FAIL';

export const CREATE_CONTACTS_LOADING = 'CREATE_CONTACTS_LOADING';
export const CREATE_CONTACTS_SUCCESS = 'CREATE_CONTACTS_SUCCESS';
export const CREATE_CONTACTS_FAIL = 'CREATE_CONTACTS_FAIL';

export const DELETE_CONTACTS_LOADING = 'DELETE_CONTACTS_LOADING';
export const DELETE_CONTACTS_SUCCESS = 'DELETE_CONTACTS_SUCCESS';
export const DELETE_CONTACTS_FAIL = 'DELETE_CONTACTS_FAIL';

export const UPDATE_CONTACTS_LOADING = 'UPDATE_CONTACTS_LOADING';
export const UPDATE_CONTACTS_SUCCESS = 'UPDATE_CONTACTS_SUCCESS';
export const UPDATE_CONTACTS_FAIL = 'UPDATE_CONTACTS_FAIL';

export const CHANGE_IS_FAVORITE = 'CHANGE_IS_FAVORITE';
